// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ReqnRollUITest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CategoriesManagementFeature : object, global::Xunit.IClassFixture<CategoriesManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Categories Management", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Category.feature"
#line hidden
        
        public CategoriesManagementFeature(CategoriesManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
    await testRunner.GivenAsync("he iniciado sesión como \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.AndAsync("navego a la página Productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Category.feature.ndjson", 54);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Insertar categoría con diferentes datos invalidos desde la página Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar categoría con diferentes datos invalidos desde la página Productos")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "El nombre es obligatorio.", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "El nombre es obligatorio.", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "El nombre es obligatorio.", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "El nombre es obligatorio.", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para los perros", "El nombre es obligatorio.", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Pro", "Debe tener al menos 3 caracteres.", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "Debe tener al menos 3 caracteres.", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto para ancianos@$%", "Debe tener al menos 3 caracteres.", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto saludable para los perros", "Debe tener al menos 3 caracteres.", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "Debe tener al menos 3 caracteres.", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No puede tener más de 50 caracteres.", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto para ancianos@$%", "No puede tener más de 50 caracteres.", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto saludable para los perros", "No puede tener más de 50 caracteres.", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "No puede tener más de 50 caracteres.", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Pro", "No puede tener más de 50 caracteres.", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Este es un producto para ancianos@$%", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Este es un producto saludable para los perros", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "[VACIO]", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Pro", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "[VACIO]", "La descripción es obligatoria.", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "Pro", "Debe tener al menos 5 caracteres.", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No puede tener más de 500 caracteres.", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "Este es un producto para ancianos@$%", "No se permiten caracteres extraños.", "23", new string[0])]
        public async global::System.Threading.Tasks.Task InsertarCategoriaConDiferentesDatosInvalidosDesdeLaPaginaProductos(string name, string description, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar categoría con diferentes datos invalidos desde la página Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 9
    await testRunner.WhenAsync("hago click en el botón \"Agregar Categoría\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.AndAsync(string.Format("ingreso el nombre \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync(string.Format("ingreso la descripción \"{0}\"", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("hago click en el botón \"Agregar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Insertar categoria con datos validos desde la pagina Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar categoria con datos validos desde la pagina Productos")]
        public async global::System.Threading.Tasks.Task InsertarCategoriaConDatosValidosDesdeLaPaginaProductos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar categoria con datos validos desde la pagina Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.WhenAsync("hago click en el botón \"Agregar Categoría\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.AndAsync("ingreso el nombre \"Comida para perros\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync("ingreso la descripción \"Es un producto para perros\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync("hago click en el botón \"Agregar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.ThenAsync("el modal debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.AndAsync("la categoría \"Comida para perros\" debe aparecer en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mostrar el listado de categorías en la página Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Mostrar el listado de categorías en la página Productos")]
        public async global::System.Threading.Tasks.Task MostrarElListadoDeCategoriasEnLaPaginaProductos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mostrar el listado de categorías en la página Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.GivenAsync("que existe al menos 1 categoría creada previamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.ThenAsync("debe mostrarse la tabla de categorías", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
    await testRunner.AndAsync("la tabla debe contener al menos un registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("cada registro debe mostrar enlaces \"Editar\" y \"Eliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Editar una categoría existente con datos invalidos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Editar una categoría existente con datos invalidos")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "El nombre es obligatorio.", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "El nombre es obligatorio.", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "El nombre es obligatorio.", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "El nombre es obligatorio.", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para los perros", "El nombre es obligatorio.", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Pro", "Debe tener al menos 3 caracteres.", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "Debe tener al menos 3 caracteres.", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto para ancianos@$%", "Debe tener al menos 3 caracteres.", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto saludable para los perros", "Debe tener al menos 3 caracteres.", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "Debe tener al menos 3 caracteres.", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No puede tener más de 50 caracteres.", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto para ancianos@$%", "No puede tener más de 50 caracteres.", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto saludable para los perros", "No puede tener más de 50 caracteres.", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "No puede tener más de 50 caracteres.", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Pro", "No puede tener más de 50 caracteres.", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Este es un producto para ancianos@$%", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Este es un producto saludable para los perros", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "[VACIO]", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", "Pro", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros@", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No se permiten números, espacios seguidos ni espacios al principio ni el final.", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "[VACIO]", "La descripción es obligatoria.", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "Pro", "Debe tener al menos 5 caracteres.", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "No puede tener más de 500 caracteres.", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("Comida para perros", "Este es un producto para ancianos@$%", "No se permiten caracteres extraños.", "49", new string[0])]
        public async global::System.Threading.Tasks.Task EditarUnaCategoriaExistenteConDatosInvalidos(string name, string description, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar una categoría existente con datos invalidos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("que existe una categoría creada previamente con nombre “Comida para perros” con d" +
                        "escripción “Este es un producto saludable para los perros”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.WhenAsync("hago click en el botón “Editar” de la categoría “Comida para perros”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
    await testRunner.AndAsync(string.Format("actualizo el nombre a \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.AndAsync(string.Format("actualizo la descripción a \"{0}\"", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("hago click en el botón \"Actualizar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Editar una categoría existente con datos validos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Editar una categoría existente con datos validos")]
        public async global::System.Threading.Tasks.Task EditarUnaCategoriaExistenteConDatosValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "50";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar una categoría existente con datos validos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 95
    await testRunner.GivenAsync("que existe una categoría creada previamente con nombre “Comida para perros” con d" +
                        "escripción “Este es un producto saludable para los perros”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
    await testRunner.WhenAsync("hago click en el botón “Editar” de la categoría “Comida para perros”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
    await testRunner.AndAsync("actualizo el nombre a \"Comida para gatos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync("actualizo la descripción a \"Este es un producto saludable para los gatos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
    await testRunner.AndAsync("hago click en el botón \"Actualizar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
    await testRunner.ThenAsync("el modal debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
    await testRunner.AndAsync("la categoria se actualizo correctamente en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Deshabilitar categoría correctamente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Categories Management")]
        [global::Xunit.TraitAttribute("Description", "Deshabilitar categoría correctamente")]
        public async global::System.Threading.Tasks.Task DeshabilitarCategoriaCorrectamente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "51";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deshabilitar categoría correctamente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 104
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 105
    await testRunner.GivenAsync("existe una categoría activa con nombre “Comida para gatos” y descripción “Este es" +
                        " un producto saludable para los gatos”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
    await testRunner.WhenAsync("hago click en el botón Deshabilitar de la categoría “Comida para gatos”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.AndAsync("confirmo la eliminación en el modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.ThenAsync("la categoría “Comida para gatos” ya aparece como “Inactivo” en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CategoriesManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CategoriesManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
