// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ReqnRollUITest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProductsManagementFeature : object, global::Xunit.IClassFixture<ProductsManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Products Management", "    Como administrador del sistema\r\n    Quiero gestionar los productos\r\n    Para " +
                "organizar el inventario correctamente", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Product.feature"
#line hidden
        
        public ProductsManagementFeature(ProductsManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("he iniciado sesión como \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("navego a la página Productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Product.feature.ndjson", 74);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Insertar producto con diferentes datos invalidos desde la página Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar producto con diferentes datos invalidos desde la página Productos")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "1fdv2", "-12", "El nombre es obligatorio.", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "12", "32768", "El nombre es obligatorio.", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "125421", "10", "El nombre es obligatorio.", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para ancianos", "32768", "[VACIO]", "El nombre es obligatorio.", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Pro", "12", "10", "Debe tener al menos 3 caracteres.", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "125421", "[VACIO]", "Debe tener al menos 3 caracteres.", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto para ancianos@$%", "32768", "-12", "Debe tener al menos 3 caracteres.", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto saludable para ancianos", "12354", "[VACIO]", "Debe tener al menos 3 caracteres.", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "[VACIO]", "-12", "Debe tener al menos 3 caracteres.", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "12354", "32768", "Debe tener al menos 3 caracteres.", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "1fdv2", "[VACIO]", "Debe tener un máximo de 100 caracteres.", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto para ancianos@$%", "32768", "-12", "Debe tener un máximo de 100 caracteres.", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto saludable para ancianos", "[VACIO]", "32768", "Debe tener un máximo de 100 caracteres.", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "1fdv2", "10", "Debe tener un máximo de 100 caracteres.", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "12", "[VACIO]", "Debe tener un máximo de 100 caracteres.", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Pro", "125421", "-12", "Debe tener un máximo de 100 caracteres.", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Este es un producto para ancianos@$%", "[VACIO]", "10", "No se permiten caracteres extraños o sólo números.", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Este es un producto saludable para ancianos", "1fdv2", "[VACIO]", "No se permiten caracteres extraños o sólo números.", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "[VACIO]", "12", "-12", "No se permiten caracteres extraños o sólo números.", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "[VACIO]", "125421", "[VACIO]", "No se permiten caracteres extraños o sólo números.", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Pro", "32768", "-12", "No se permiten caracteres extraños o sólo números.", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "12354", "32768", "No se permiten caracteres extraños o sólo números.", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Este es un producto saludable para ancianos", "12", "[VACIO]", "Debe ingresar 5 digitos.", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "[VACIO]", "125421", "-12", "La descripción es obligatoria.", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "[VACIO]", "32768", "32768", "La descripción es obligatoria.", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Pro", "12354", "10", "Debe tener al menos 5 caracteres.", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "[VACIO]", "[VACIO]", "Debe tener un máximo de 500 caracteres.", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Este es un producto para ancianos@$%", "1fdv2", "-12", "No se permiten caracteres extraños.", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "32768", "10", "El nombre es obligatorio.", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "12354", "[VACIO]", "El nombre es obligatorio.", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "[VACIO]", "-12", "El nombre es obligatorio.", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "1fdv2", "[VACIO]", "El nombre es obligatorio.", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "12", "-12", "El nombre es obligatorio.", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para ancianos", "125421", "32768", "El nombre es obligatorio.", "33", new string[0])]
        public async global::System.Threading.Tasks.Task InsertarProductoConDiferentesDatosInvalidosDesdeLaPaginaProductos(string name, string description, string serialCode, string stock, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("SerialCode", serialCode);
            argumentsOfScenario.Add("Stock", stock);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar producto con diferentes datos invalidos desde la página Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("hago click en el botón \"Agregar Producto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.AndAsync(string.Format("ingreso el nombre \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("ingreso la descripción \"{0}\"", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("ingreso el codigo serial \"{0}\"", serialCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("ingreso el total stock \"{0}\"", stock), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("hago click en el botón \"Agregar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Insertar producto con datos validso desde la pagina Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar producto con datos validso desde la pagina Productos")]
        public async global::System.Threading.Tasks.Task InsertarProductoConDatosValidsoDesdeLaPaginaProductos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "34";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar producto con datos validso desde la pagina Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 59
    await testRunner.WhenAsync("hago click en el botón \"Agregar Producto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.AndAsync("ingreso el nombre \"Laptop Dell XPS 15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("ingreso la descripción \"Este es un producto tecnologico\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.AndAsync("ingreso el codigo serial \"23456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.AndAsync("ingreso el total stock \"10\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("hago click en el botón \"Agregar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.ThenAsync("el modal debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync("el producto \"Laptop Dell XPS 15\" debe aparecer en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mostrar el listado de productos en la página Productos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Mostrar el listado de productos en la página Productos")]
        public async global::System.Threading.Tasks.Task MostrarElListadoDeProductosEnLaPaginaProductos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "35";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mostrar el listado de productos en la página Productos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 70
    await testRunner.GivenAsync("que existe al menos 1 producto creado previamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.ThenAsync("debe mostrarse la tabla de productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("la tablas debe contener al menos un registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("cada registro debe mostrar enlaces \"Editar\" y \"Eliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Editar un producto existente con datos invalidos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Editar un producto existente con datos invalidos")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "1fdv2", "-12", "El nombre es obligatorio.", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "12", "32768", "El nombre es obligatorio.", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "125421", "10", "El nombre es obligatorio.", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para ancianos", "32768", "[VACIO]", "El nombre es obligatorio.", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Pro", "12", "10", "Debe tener al menos 3 caracteres.", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "125421", "[VACIO]", "Debe tener al menos 3 caracteres.", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto para ancianos@$%", "32768", "-12", "Debe tener al menos 3 caracteres.", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "Este es un producto saludable para ancianos", "12354", "[VACIO]", "Debe tener al menos 3 caracteres.", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "[VACIO]", "-12", "Debe tener al menos 3 caracteres.", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("Pe", "[VACIO]", "12354", "32768", "Debe tener al menos 3 caracteres.", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "1fdv2", "[VACIO]", "Debe tener un máximo de 100 caracteres.", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto para ancianos@$%", "32768", "-12", "Debe tener un máximo de 100 caracteres.", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Este es un producto saludable para ancianos", "[VACIO]", "32768", "Debe tener un máximo de 100 caracteres.", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "1fdv2", "10", "Debe tener un máximo de 100 caracteres.", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "[VACIO]", "12", "[VACIO]", "Debe tener un máximo de 100 caracteres.", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("Set completo de juguetes educativos interactivos de madera, plástico y materiales" +
            " seguros para niños de 3 a 12 años", "Pro", "125421", "-12", "Debe tener un máximo de 100 caracteres.", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Este es un producto para ancianos@$%", "[VACIO]", "10", "No se permiten caracteres extraños o sólo números.", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Este es un producto saludable para ancianos", "1fdv2", "[VACIO]", "No se permiten caracteres extraños o sólo números.", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "[VACIO]", "12", "-12", "No se permiten caracteres extraños o sólo números.", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "[VACIO]", "125421", "[VACIO]", "No se permiten caracteres extraños o sólo números.", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", "Pro", "32768", "-12", "No se permiten caracteres extraños o sólo números.", "56", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop$ Dell XPS 14@", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "12354", "32768", "No se permiten caracteres extraños o sólo números.", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Este es un producto saludable para ancianos", "12", "[VACIO]", "Debe ingresar 5 digitos.", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "[VACIO]", "125421", "-12", "La descripción es obligatoria.", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "[VACIO]", "32768", "32768", "La descripción es obligatoria.", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Pro", "12354", "10", "Debe tener al menos 5 caracteres.", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "[VACIO]", "[VACIO]", "Debe tener un máximo de 500 caracteres.", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("Laptop Dell XPS 14", "Este es un producto para ancianos@$%", "1fdv2", "-12", "No se permiten caracteres extraños.", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "32768", "10", "El nombre es obligatorio.", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "12354", "[VACIO]", "El nombre es obligatorio.", "65", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Pro", "[VACIO]", "-12", "El nombre es obligatorio.", "66", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", @"Este innovador set de juguetes educativos combina diversión y aprendizaje, incluyendo bloques de construcción, figuras de animales, letras y números, rompecabezas y materiales interactivos diseñados para estimular la creatividad, la coordinación, la motricidad fina y el pensamiento lógico en niños de diferentes edades. Fabricado con materiales seguros y duraderos, su diseño atractivo permite horas de entretenimiento mientras fomenta habilidades cognitivas esenciales, promoviendo el desarrollo integral", "1fdv2", "[VACIO]", "El nombre es obligatorio.", "67", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto para ancianos@$%", "12", "-12", "El nombre es obligatorio.", "68", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "Este es un producto saludable para ancianos", "125421", "32768", "El nombre es obligatorio.", "69", new string[0])]
        public async global::System.Threading.Tasks.Task EditarUnProductoExistenteConDatosInvalidos(string name, string description, string serialCode, string stock, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("SerialCode", serialCode);
            argumentsOfScenario.Add("Stock", stock);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar un producto existente con datos invalidos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 77
    await testRunner.GivenAsync("que existe un producto creado previamente con nombre “Laptop Dell XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
    await testRunner.WhenAsync("hago click en el botón “Editar” del producto “Laptop Dell XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
    await testRunner.AndAsync(string.Format("actualizo el nombre a \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.AndAsync(string.Format("actualizo la descripción a \"{0}\"", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
    await testRunner.AndAsync(string.Format("actualizo el codigo serial a \"{0}\"", serialCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync(string.Format("actualizo el stock a \"{0}\"", stock), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("hago click en el botón \"Actualizar\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Editar un producto existente con datos validos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Editar un producto existente con datos validos")]
        public async global::System.Threading.Tasks.Task EditarUnProductoExistenteConDatosValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "70";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar un producto existente con datos validos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 123
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 124
    await testRunner.GivenAsync("que existe un producto creado previamente con nombre “Laptop Dell XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 125
    await testRunner.WhenAsync("hago click en el botón “Editar” del producto “Laptop Dell XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
    await testRunner.AndAsync("actualizo el nombre a \"Tablet XPS 15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.AndAsync("actualizo la descripción a \"Este es un producto tecnologico del 2022\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
    await testRunner.AndAsync("actualizo el codigo serial a \"23456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
    await testRunner.AndAsync("actualizo el stock a \"20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.AndAsync("hago click en el botón \"Guardar Cambios\" del formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
    await testRunner.ThenAsync("el modal debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
    await testRunner.AndAsync("el producto se actualizo correctamente en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Deshabilitar producto correctamente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Products Management")]
        [global::Xunit.TraitAttribute("Description", "Deshabilitar producto correctamente")]
        public async global::System.Threading.Tasks.Task DeshabilitarProductoCorrectamente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "71";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deshabilitar producto correctamente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 135
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 136
    await testRunner.GivenAsync("existe un producto activo con nombre “Tablet XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
    await testRunner.WhenAsync("hago click en el botón Deshabilitar del producto “Tablet XPS 15”", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 138
    await testRunner.AndAsync("confirmo la eliminación en el modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.ThenAsync("el producto “Tablet XPS 15” ya aparece como “Inactivo” en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ProductsManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ProductsManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
