// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ReqnRollUITest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SuppliersManagementFeature : object, global::Xunit.IClassFixture<SuppliersManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Suppliers Management", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Supplier.feature"
#line hidden
        
        public SuppliersManagementFeature(SuppliersManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
    await testRunner.GivenAsync("he iniciado sesión como \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.AndAsync("navego a la página Proveedores", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Supplier.feature.ndjson", 104);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Insertar proveedor con diferentes datos invalidos desde la página Proveedores")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar proveedor con diferentes datos invalidos desde la página Proveedores")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "El nombre es obligatorio.", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456", "10203040", "ventas@proveedor.bo", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El nombre es obligatorio.", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "445123", "10203040-5", "ventasproveedor.com", "Ana María de la O", "C/1", "El nombre es obligatorio.", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "12345", "123456-7", "ventas@proveedorcom", "A", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El nombre es obligatorio.", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456789", "1234567890123-4", "ventas @proveedor.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "[VACIO]", "El nombre es obligatorio.", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "717-23-456", "1020A304", "a@b.c", "José-Luis", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El nombre es obligatorio.", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "1020 3040", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "[VACIO]", "C/1", "El nombre es obligatorio.", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "71723456", "10203040-5", "ventas@proveedorcom", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener un formato válido (ej. usuario@dominio.com).", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "445123", "123456-7", "ventas @proveedor.com", "José-Luis", "C/1", "Formato inválido. Ejemplo: 12345678-9", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "12345", "1234567890123-4", "a@b.c", "[VACIO]", "[VACIO]", "Formato inválido. Ejemplo: 12345678-9", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "71723456789", "1020A304", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "[VACIO]", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Formato inválido. Ejemplo: 12345678-9", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "717-23-456", "1020 3040", "[VACIO]", "1234567", "C/1", "Formato inválido. Ejemplo: 12345678-9", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "[VACIO]", "[VACIO]", "ventas@proveedor.bo", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El NIT es obligatorio.", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "[VACIO]", "[VACIO]", "ventasproveedor.com", "A", "[VACIO]", "El teléfono es obligatorio.", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "445123", "1234567890123-4", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "1234567", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "12345", "1020A304", "[VACIO]", "Ana María de la O", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456789", "1020 3040", "ventas@proveedor.bo", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "717-23-456", "[VACIO]", "ventasproveedor.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "C/1", "No puede ser solo números ni contener caracteres inválidos.", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "[VACIO]", "10203040", "ventas@proveedorcom", "José-Luis", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456", "10203040-5", "ventas @proveedor.com", "[VACIO]", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "445123", "123456-7", "a@b.c", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "12345", "1020 3040", "ventas@proveedor.bo", "Ana María de la O", "[VACIO]", "Debe tener al menos 4 caracteres.", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "71723456789", "[VACIO]", "ventasproveedor.com", "[VACIO]", "C/1", "Debe tener al menos 4 caracteres.", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "717-23-456", "10203040", "ventas@proveedorcom", "1234567", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener al menos 4 caracteres.", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "[VACIO]", "10203040-5", "ventas @proveedor.com", "A", "[VACIO]", "Debe tener al menos 4 caracteres.", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "71723456", "123456-7", "a@b.c", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "C/1", "Debe tener al menos 4 caracteres.", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "445123", "1234567890123-4", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "José-Luis", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener al menos 4 caracteres.", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "12345", "1020A304", "[VACIO]", "Ana María de la O", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener al menos 4 caracteres.", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "717-23-456", "123456-7", "[VACIO]", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener menos de 31 caracteres.", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "[VACIO]", "1234567890123-4", "ventas@proveedorcom", "José-Luis", "[VACIO]", "Debe tener menos de 31 caracteres.", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456", "1020A304", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "A", "[VACIO]", "Debe tener menos de 31 caracteres.", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "445123", "1020 3040", "[VACIO]", "1234567", "C/1", "Debe tener menos de 31 caracteres.", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "12345", "[VACIO]", "ventas@proveedor.bo", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener menos de 31 caracteres.", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456789", "10203040", "ventasproveedor.com", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener menos de 31 caracteres.", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456", "10203040-5", "a@b.c", "[VACIO]", "[VACIO]", "Debe tener menos de 31 caracteres.", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "445123", "[VACIO]", "a@b.c", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "12345", "10203040", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "71723456789", "10203040-5", "[VACIO]", "José-Luis", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "717-23-456", "1234567890123-4", "ventas@proveedor.bo", "[VACIO]", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "[VACIO]", "1020A304", "ventasproveedor.com", "1234567", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "71723456", "1020 3040", "ventas@proveedorcom", "Ana María de la O", "C/1", "No puede ser solo números ni contener caracteres inválidos.", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "445123", "123456-7", "ventas @proveedor.com", "[VACIO]", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456", "1234567890123-4", "a@b.c", "Ana María de la O", "C/1", "El nombre es obligatorio.", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "717-23-456", "[VACIO]", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El NIT es obligatorio.", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456789", "10203040", "a@b.c", "José-Luis", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "[VACIO]", "1020A304", "ventas@proveedor.bo", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener al menos 4 caracteres.", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "445123", "123456-7", "ventasproveedor.com", "1234567", "C/1", "Debe tener menos de 31 caracteres.", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "12345", "10203040-5", "ventas@proveedorcom", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456789", "1020 3040", "[VACIO]", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El nombre es obligatorio.", "48", new string[0])]
        public async global::System.Threading.Tasks.Task InsertarProveedorConDiferentesDatosInvalidosDesdeLaPaginaProveedores(string name, string phone, string nit, string email, string contact, string address, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Phone", phone);
            argumentsOfScenario.Add("Nit", nit);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Contact", contact);
            argumentsOfScenario.Add("Address", address);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar proveedor con diferentes datos invalidos desde la página Proveedores", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 9
    await testRunner.WhenAsync("hago click en el botón \"Agregar Proveedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.AndAsync(string.Format("ingreso el nombre del proveedor \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync(string.Format("ingreso el nit \"{0}\"", nit), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync(string.Format("ingreso el telefono \"{0}\"", phone), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync(string.Format("ingreso el email \"{0}\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("ingreso el nombre de contacto \"{0}\"", contact), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("ingreso la direccion \"{0}\"", address), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("hago click en el botón \"Guardar\" del formulario de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje de proveedor \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Insertar proveedor con datos validos desde la pagina Proveedores")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Insertar proveedor con datos validos desde la pagina Proveedores")]
        public async global::System.Threading.Tasks.Task InsertarProveedorConDatosValidosDesdeLaPaginaProveedores()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "49";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar proveedor con datos validos desde la pagina Proveedores", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 72
    await testRunner.WhenAsync("hago click en el botón \"Agregar Proveedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.AndAsync("ingreso el nombre del proveedor \"DistribuidoraABC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync("ingreso el nit \"12365487\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync("ingreso el telefono \"25662147\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("ingreso el email \"ventas@gmail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("ingreso el nombre de contacto \"Juan Perez\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("ingreso la direccion \"Av. Siempre Viva 123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.AndAsync("hago click en el botón \"Guardar\" del formulario de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.ThenAsync("el modal de proveedor debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("el proveedor \"Distribuidora ABC\" debe aparecer en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mostrar el listado de proveedores en la página Proveedores")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Mostrar el listado de proveedores en la página Proveedores")]
        public async global::System.Threading.Tasks.Task MostrarElListadoDeProveedoresEnLaPaginaProveedores()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "50";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mostrar el listado de proveedores en la página Proveedores", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 85
    await testRunner.GivenAsync("que existe al menos 1 proveedor creado previamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.ThenAsync("debe mostrarse la tabla de proveedores", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("la tabla de proveedores debe contener al menos un registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.AndAsync("cada registro de proveedor debe mostrar enlaces \"Editar\" y \"Eliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Editar un proveedor existente con datos invalidos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Editar un proveedor existente con datos invalidos")]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "[VACIO]", "El nombre es obligatorio.", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456", "10203040", "ventas@proveedor.bo", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El nombre es obligatorio.", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "445123", "10203040-5", "ventasproveedor.com", "Ana María de la O", "C/1", "El nombre es obligatorio.", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "12345", "123456-7", "ventas@proveedorcom", "A", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El nombre es obligatorio.", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456789", "1234567890123-4", "ventas @proveedor.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "[VACIO]", "El nombre es obligatorio.", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "717-23-456", "1020A304", "a@b.c", "José-Luis", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El nombre es obligatorio.", "56", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "[VACIO]", "1020 3040", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "[VACIO]", "C/1", "El nombre es obligatorio.", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "71723456", "10203040-5", "ventas@proveedorcom", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener un formato válido (ej. usuario@dominio.com).", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "445123", "123456-7", "ventas @proveedor.com", "José-Luis", "C/1", "Formato inválido. Ejemplo: 12345678-9", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "12345", "1234567890123-4", "a@b.c", "[VACIO]", "[VACIO]", "Formato inválido. Ejemplo: 12345678-9", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "71723456789", "1020A304", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "[VACIO]", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Formato inválido. Ejemplo: 12345678-9", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "717-23-456", "1020 3040", "[VACIO]", "1234567", "C/1", "Formato inválido. Ejemplo: 12345678-9", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "[VACIO]", "[VACIO]", "ventas@proveedor.bo", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El NIT es obligatorio.", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "[VACIO]", "[VACIO]", "ventasproveedor.com", "A", "[VACIO]", "El teléfono es obligatorio.", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "445123", "1234567890123-4", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "1234567", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "65", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "12345", "1020A304", "[VACIO]", "Ana María de la O", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "66", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456789", "1020 3040", "ventas@proveedor.bo", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "67", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "717-23-456", "[VACIO]", "ventasproveedor.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "C/1", "No puede ser solo números ni contener caracteres inválidos.", "68", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "[VACIO]", "10203040", "ventas@proveedorcom", "José-Luis", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "69", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456", "10203040-5", "ventas @proveedor.com", "[VACIO]", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "70", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "445123", "123456-7", "a@b.c", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "71", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "12345", "1020 3040", "ventas@proveedor.bo", "Ana María de la O", "[VACIO]", "Debe tener al menos 4 caracteres.", "72", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "71723456789", "[VACIO]", "ventasproveedor.com", "[VACIO]", "C/1", "Debe tener al menos 4 caracteres.", "73", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "717-23-456", "10203040", "ventas@proveedorcom", "1234567", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener al menos 4 caracteres.", "74", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "[VACIO]", "10203040-5", "ventas @proveedor.com", "A", "[VACIO]", "Debe tener al menos 4 caracteres.", "75", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "71723456", "123456-7", "a@b.c", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "C/1", "Debe tener al menos 4 caracteres.", "76", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "445123", "1234567890123-4", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "José-Luis", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener al menos 4 caracteres.", "77", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "12345", "1020A304", "[VACIO]", "Ana María de la O", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener al menos 4 caracteres.", "78", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "717-23-456", "123456-7", "[VACIO]", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener menos de 31 caracteres.", "79", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "[VACIO]", "1234567890123-4", "ventas@proveedorcom", "José-Luis", "[VACIO]", "Debe tener menos de 31 caracteres.", "80", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456", "1020A304", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "A", "[VACIO]", "Debe tener menos de 31 caracteres.", "81", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "445123", "1020 3040", "[VACIO]", "1234567", "C/1", "Debe tener menos de 31 caracteres.", "82", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "12345", "[VACIO]", "ventas@proveedor.bo", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener menos de 31 caracteres.", "83", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456789", "10203040", "ventasproveedor.com", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "Debe tener menos de 31 caracteres.", "84", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "71723456", "10203040-5", "a@b.c", "[VACIO]", "[VACIO]", "Debe tener menos de 31 caracteres.", "85", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "445123", "[VACIO]", "a@b.c", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "86", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "12345", "10203040", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "87", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "71723456789", "10203040-5", "[VACIO]", "José-Luis", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "88", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "717-23-456", "1234567890123-4", "ventas@proveedor.bo", "[VACIO]", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "89", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "[VACIO]", "1020A304", "ventasproveedor.com", "1234567", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "90", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "71723456", "1020 3040", "ventas@proveedorcom", "Ana María de la O", "C/1", "No puede ser solo números ni contener caracteres inválidos.", "91", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "445123", "123456-7", "ventas @proveedor.com", "[VACIO]", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "No puede ser solo números ni contener caracteres inválidos.", "92", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456", "1234567890123-4", "a@b.c", "Ana María de la O", "C/1", "El nombre es obligatorio.", "93", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567", "717-23-456", "[VACIO]", "un-correo-electronico-demasiado-largo@dominio-gigante.com", "A", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "El NIT es obligatorio.", "94", new string[0])]
        [global::Xunit.InlineDataAttribute("Ferretería 24 Horas+", "71723456789", "10203040", "a@b.c", "José-Luis", "[VACIO]", "No puede ser solo números ni contener caracteres inválidos.", "95", new string[0])]
        [global::Xunit.InlineDataAttribute("Sol", "[VACIO]", "1020A304", "ventas@proveedor.bo", "Este es un nombre de contacto extremadamente largo que excede el límite de 50 car" +
            "acteres", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "Debe tener al menos 4 caracteres.", "96", new string[0])]
        [global::Xunit.InlineDataAttribute("Este es un nombre de proveedor demasiado largo para ser válido", "445123", "123456-7", "ventasproveedor.com", "1234567", "C/1", "Debe tener menos de 31 caracteres.", "97", new string[0])]
        [global::Xunit.InlineDataAttribute("Import-Sur, S.R.L.+", "12345", "10203040-5", "ventas@proveedorcom", "1234567", "Av. Oquendo #555, Edificio \"Sol\" - @Oficina4", "No puede ser solo números ni contener caracteres inválidos.", "98", new string[0])]
        [global::Xunit.InlineDataAttribute("[VACIO]", "71723456789", "1020 3040", "[VACIO]", "Ana María de la O", "Esta es una dirección de ejemplo increíblemente larga para exceder el límite máxi" +
            "mo de cien caracteres y ver si la validación funciona correctamente.", "El nombre es obligatorio.", "99", new string[0])]
        public async global::System.Threading.Tasks.Task EditarUnProveedorExistenteConDatosInvalidos(string name, string phone, string nit, string email, string contact, string address, string expectedResult, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Phone", phone);
            argumentsOfScenario.Add("Nit", nit);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Contact", contact);
            argumentsOfScenario.Add("Address", address);
            argumentsOfScenario.Add("ExpectedResult", expectedResult);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar un proveedor existente con datos invalidos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 91
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 92
    await testRunner.GivenAsync("que existe un proveedor creado previamente con nombre \"Distribuidora ABC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
    await testRunner.WhenAsync("hago click en el botón \"Editar\" del proveedor \"Distribuidora ABC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
    await testRunner.AndAsync(string.Format("actualizo el nombre del proveedor a \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.AndAsync(string.Format("actualizo el nit a \"{0}\"", nit), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
    await testRunner.AndAsync(string.Format("actualizo el telefono a \"{0}\"", phone), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
    await testRunner.AndAsync(string.Format("actualizo el email a \"{0}\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync(string.Format("actualizo el nombre de contacto a \"{0}\"", contact), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
    await testRunner.AndAsync(string.Format("actualizo la direccion a \"{0}\"", address), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
    await testRunner.AndAsync("hago click en el botón \"Guardar Cambios\" del formulario de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
    await testRunner.ThenAsync(string.Format("se debe mostrar el mensaje de proveedor \"{0}\"", expectedResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Editar un proveedor existente con datos validos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Editar un proveedor existente con datos validos")]
        public async global::System.Threading.Tasks.Task EditarUnProveedorExistenteConDatosValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "100";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar un proveedor existente con datos validos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 155
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 156
    await testRunner.GivenAsync("que existe un proveedor creado previamente con nombre \"Distribuidora ABC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
    await testRunner.WhenAsync("hago click en el botón \"Editar\" del proveedor \"Distribuidora ABC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 158
    await testRunner.AndAsync("actualizo el nombre del proveedor a \"Distribuidora XYZ\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
    await testRunner.AndAsync("actualizo el nit a \"12159853215\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
    await testRunner.AndAsync("actualizo el telefono a \"63258454\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
    await testRunner.AndAsync("actualizo el email a \"contacto@gmail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
    await testRunner.AndAsync("actualizo el nombre de contacto a \"Maria Lopez\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
    await testRunner.AndAsync("actualizo la direccion a \"Calle Falsa 456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
    await testRunner.AndAsync("hago click en el botón \"Guardar Cambios\" del formulario de proveedor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
    await testRunner.ThenAsync("el modal de proveedor debe cerrarse automaticamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 166
    await testRunner.AndAsync("el proveedor se actualizo correctamente en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Deshabilitar proveedor correctamente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Suppliers Management")]
        [global::Xunit.TraitAttribute("Description", "Deshabilitar proveedor correctamente")]
        public async global::System.Threading.Tasks.Task DeshabilitarProveedorCorrectamente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "101";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deshabilitar proveedor correctamente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 169
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 170
    await testRunner.GivenAsync("existe un proveedor activo con nombre \"Distribuidora XYZ\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
    await testRunner.WhenAsync("hago click en el botón Deshabilitar del proveedor \"Distribuidora XYZ\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 172
    await testRunner.AndAsync("confirmo la eliminación del proveedor en el modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
    await testRunner.ThenAsync("el proveedor \"Distribuidora XYZ\" ya aparece como \"Inactivo\" en la tabla", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SuppliersManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SuppliersManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
